# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/functionCallingRecommend/functionCallingRecommend.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n=proto/functionCallingRecommend/functionCallingRecommend.proto\x12\x18\x66unctionCallingRecommend\";\n\x16\x46unctionCallingRequest\x12\x10\n\x08memberId\x18\x01 \x01(\x03\x12\x0f\n\x07\x63ommand\x18\x02 \x01(\t\"-\n\x17\x46unctionCallingResponse\x12\x12\n\nsongInfoId\x18\x01 \x03(\x03\x32\xa6\x01\n\x18\x66unctionCallingRecommend\x12\x89\x01\n GetFunctionCallingRecommendation\x12\x30.functionCallingRecommend.FunctionCallingRequest\x1a\x31.functionCallingRecommend.FunctionCallingResponse\"\x00\x62\x06proto3')



_FUNCTIONCALLINGREQUEST = DESCRIPTOR.message_types_by_name['FunctionCallingRequest']
_FUNCTIONCALLINGRESPONSE = DESCRIPTOR.message_types_by_name['FunctionCallingResponse']
FunctionCallingRequest = _reflection.GeneratedProtocolMessageType('FunctionCallingRequest', (_message.Message,), {
  'DESCRIPTOR' : _FUNCTIONCALLINGREQUEST,
  '__module__' : 'proto.functionCallingRecommend.functionCallingRecommend_pb2'
  # @@protoc_insertion_point(class_scope:functionCallingRecommend.FunctionCallingRequest)
  })
_sym_db.RegisterMessage(FunctionCallingRequest)

FunctionCallingResponse = _reflection.GeneratedProtocolMessageType('FunctionCallingResponse', (_message.Message,), {
  'DESCRIPTOR' : _FUNCTIONCALLINGRESPONSE,
  '__module__' : 'proto.functionCallingRecommend.functionCallingRecommend_pb2'
  # @@protoc_insertion_point(class_scope:functionCallingRecommend.FunctionCallingResponse)
  })
_sym_db.RegisterMessage(FunctionCallingResponse)

_FUNCTIONCALLINGRECOMMEND = DESCRIPTOR.services_by_name['functionCallingRecommend']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FUNCTIONCALLINGREQUEST._serialized_start=91
  _FUNCTIONCALLINGREQUEST._serialized_end=150
  _FUNCTIONCALLINGRESPONSE._serialized_start=152
  _FUNCTIONCALLINGRESPONSE._serialized_end=197
  _FUNCTIONCALLINGRECOMMEND._serialized_start=200
  _FUNCTIONCALLINGRECOMMEND._serialized_end=366
# @@protoc_insertion_point(module_scope)
