# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto.functionCallingRecommend import functionCallingRecommend_pb2 as proto_dot_functionCallingRecommend_dot_functionCallingRecommend__pb2


class functionCallingRecommendStub(object):
    """LangChain 서비스
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetFunctionCallingRecommendation = channel.unary_unary(
                '/functionCallingRecommend.functionCallingRecommend/GetFunctionCallingRecommendation',
                request_serializer=proto_dot_functionCallingRecommend_dot_functionCallingRecommend__pb2.FunctionCallingRequest.SerializeToString,
                response_deserializer=proto_dot_functionCallingRecommend_dot_functionCallingRecommend__pb2.FunctionCallingResponse.FromString,
                )


class functionCallingRecommendServicer(object):
    """LangChain 서비스
    """

    def GetFunctionCallingRecommendation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_functionCallingRecommendServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetFunctionCallingRecommendation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFunctionCallingRecommendation,
                    request_deserializer=proto_dot_functionCallingRecommend_dot_functionCallingRecommend__pb2.FunctionCallingRequest.FromString,
                    response_serializer=proto_dot_functionCallingRecommend_dot_functionCallingRecommend__pb2.FunctionCallingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'functionCallingRecommend.functionCallingRecommend', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class functionCallingRecommend(object):
    """LangChain 서비스
    """

    @staticmethod
    def GetFunctionCallingRecommendation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/functionCallingRecommend.functionCallingRecommend/GetFunctionCallingRecommendation',
            proto_dot_functionCallingRecommend_dot_functionCallingRecommend__pb2.FunctionCallingRequest.SerializeToString,
            proto_dot_functionCallingRecommend_dot_functionCallingRecommend__pb2.FunctionCallingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
