# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto.userProfileRecommend import userProfileRecommend_pb2 as userProfileRecommend_dot_userProfileRecommend__pb2


class UserProfileStub(object):
    """UserProfile 서비스
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateUserProfile = channel.unary_unary(
                '/userProfileRecommend.UserProfile/CreateUserProfile',
                request_serializer=userProfileRecommend_dot_userProfileRecommend__pb2.ProfileRequest.SerializeToString,
                response_deserializer=userProfileRecommend_dot_userProfileRecommend__pb2.ProfileResponse.FromString,
                )


class UserProfileServicer(object):
    """UserProfile 서비스
    """

    def CreateUserProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserProfileServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateUserProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUserProfile,
                    request_deserializer=userProfileRecommend_dot_userProfileRecommend__pb2.ProfileRequest.FromString,
                    response_serializer=userProfileRecommend_dot_userProfileRecommend__pb2.ProfileResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'userProfileRecommend.UserProfile', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UserProfile(object):
    """UserProfile 서비스
    """

    @staticmethod
    def CreateUserProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/userProfileRecommend.UserProfile/CreateUserProfile',
            userProfileRecommend_dot_userProfileRecommend__pb2.ProfileRequest.SerializeToString,
            userProfileRecommend_dot_userProfileRecommend__pb2.ProfileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
