# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: userProfileRecommend/userProfileRecommend.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/userProfileRecommend/userProfileRecommend.proto\x12\x14userProfileRecommend\"@\n\x0eProfileRequest\x12\x10\n\x08memberId\x18\x01 \x01(\x03\x12\x0c\n\x04page\x18\x02 \x01(\x05\x12\x0e\n\x06gender\x18\x03 \x01(\t\"\xb5\x01\n\x0bSimilarItem\x12\x12\n\nsongInfoId\x18\x01 \x01(\x03\x12\x10\n\x08songName\x18\x02 \x01(\t\x12\x12\n\nsingerName\x18\x03 \x01(\t\x12\x0c\n\x04isMr\x18\x04 \x01(\x08\x12\x0c\n\x04ssss\x18\x05 \x01(\t\x12\x14\n\x0c\x61udioFileUrl\x18\x06 \x01(\t\x12\r\n\x05\x61lbum\x18\x07 \x01(\t\x12\x12\n\nsongNumber\x18\x08 \x01(\x05\x12\x17\n\x0fsimilarityScore\x18\t \x01(\x02\"J\n\x0fProfileResponse\x12\x37\n\x0csimilarItems\x18\x01 \x03(\x0b\x32!.userProfileRecommend.SimilarItem2q\n\x0bUserProfile\x12\x62\n\x11\x43reateUserProfile\x12$.userProfileRecommend.ProfileRequest\x1a%.userProfileRecommend.ProfileResponse\"\x00\x62\x06proto3')



_PROFILEREQUEST = DESCRIPTOR.message_types_by_name['ProfileRequest']
_SIMILARITEM = DESCRIPTOR.message_types_by_name['SimilarItem']
_PROFILERESPONSE = DESCRIPTOR.message_types_by_name['ProfileResponse']
ProfileRequest = _reflection.GeneratedProtocolMessageType('ProfileRequest', (_message.Message,), {
  'DESCRIPTOR' : _PROFILEREQUEST,
  '__module__' : 'userProfileRecommend.userProfileRecommend_pb2'
  # @@protoc_insertion_point(class_scope:userProfileRecommend.ProfileRequest)
  })
_sym_db.RegisterMessage(ProfileRequest)

SimilarItem = _reflection.GeneratedProtocolMessageType('SimilarItem', (_message.Message,), {
  'DESCRIPTOR' : _SIMILARITEM,
  '__module__' : 'userProfileRecommend.userProfileRecommend_pb2'
  # @@protoc_insertion_point(class_scope:userProfileRecommend.SimilarItem)
  })
_sym_db.RegisterMessage(SimilarItem)

ProfileResponse = _reflection.GeneratedProtocolMessageType('ProfileResponse', (_message.Message,), {
  'DESCRIPTOR' : _PROFILERESPONSE,
  '__module__' : 'userProfileRecommend.userProfileRecommend_pb2'
  # @@protoc_insertion_point(class_scope:userProfileRecommend.ProfileResponse)
  })
_sym_db.RegisterMessage(ProfileResponse)

_USERPROFILE = DESCRIPTOR.services_by_name['UserProfile']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PROFILEREQUEST._serialized_start=73
  _PROFILEREQUEST._serialized_end=137
  _SIMILARITEM._serialized_start=140
  _SIMILARITEM._serialized_end=321
  _PROFILERESPONSE._serialized_start=323
  _PROFILERESPONSE._serialized_end=397
  _USERPROFILE._serialized_start=399
  _USERPROFILE._serialized_end=512
# @@protoc_insertion_point(module_scope)
