# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: langchainRecommend/langchainRecommend.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+langchainRecommend/langchainRecommend.proto\x12\x12langchainRecommend\"5\n\x10LangchainRequest\x12\x10\n\x08memberId\x18\x01 \x01(\x03\x12\x0f\n\x07\x63ommand\x18\x02 \x01(\t\"\xb5\x01\n\x0bSimilarItem\x12\x12\n\nsongInfoId\x18\x01 \x01(\x03\x12\x10\n\x08songName\x18\x02 \x01(\t\x12\x12\n\nsingerName\x18\x03 \x01(\t\x12\x0c\n\x04isMr\x18\x04 \x01(\x08\x12\x0c\n\x04ssss\x18\x05 \x01(\t\x12\x14\n\x0c\x61udioFileUrl\x18\x06 \x01(\t\x12\r\n\x05\x61lbum\x18\x07 \x01(\t\x12\x12\n\nsongNumber\x18\x08 \x01(\x05\x12\x17\n\x0fsimilarityScore\x18\t \x01(\x02\"J\n\x11LangchainResponse\x12\x35\n\x0csimilarItems\x18\x01 \x03(\x0b\x32\x1f.langchainRecommend.SimilarItem2\x81\x01\n\x12LangchainRecommend\x12k\n\x1aGetLangchainRecommendation\x12$.langchainRecommend.LangchainRequest\x1a%.langchainRecommend.LangchainResponse\"\x00\x62\x06proto3')



_LANGCHAINREQUEST = DESCRIPTOR.message_types_by_name['LangchainRequest']
_SIMILARITEM = DESCRIPTOR.message_types_by_name['SimilarItem']
_LANGCHAINRESPONSE = DESCRIPTOR.message_types_by_name['LangchainResponse']
LangchainRequest = _reflection.GeneratedProtocolMessageType('LangchainRequest', (_message.Message,), {
  'DESCRIPTOR' : _LANGCHAINREQUEST,
  '__module__' : 'langchainRecommend.langchainRecommend_pb2'
  # @@protoc_insertion_point(class_scope:langchainRecommend.LangchainRequest)
  })
_sym_db.RegisterMessage(LangchainRequest)

SimilarItem = _reflection.GeneratedProtocolMessageType('SimilarItem', (_message.Message,), {
  'DESCRIPTOR' : _SIMILARITEM,
  '__module__' : 'langchainRecommend.langchainRecommend_pb2'
  # @@protoc_insertion_point(class_scope:langchainRecommend.SimilarItem)
  })
_sym_db.RegisterMessage(SimilarItem)

LangchainResponse = _reflection.GeneratedProtocolMessageType('LangchainResponse', (_message.Message,), {
  'DESCRIPTOR' : _LANGCHAINRESPONSE,
  '__module__' : 'langchainRecommend.langchainRecommend_pb2'
  # @@protoc_insertion_point(class_scope:langchainRecommend.LangchainResponse)
  })
_sym_db.RegisterMessage(LangchainResponse)

_LANGCHAINRECOMMEND = DESCRIPTOR.services_by_name['LangchainRecommend']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LANGCHAINREQUEST._serialized_start=67
  _LANGCHAINREQUEST._serialized_end=120
  _SIMILARITEM._serialized_start=123
  _SIMILARITEM._serialized_end=304
  _LANGCHAINRESPONSE._serialized_start=306
  _LANGCHAINRESPONSE._serialized_end=380
  _LANGCHAINRECOMMEND._serialized_start=383
  _LANGCHAINRECOMMEND._serialized_end=512
# @@protoc_insertion_point(module_scope)
