# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto.langchainRecommend import langchainRecommend_pb2 as langchainRecommend_dot_langchainRecommend__pb2


class LangchainRecommendStub(object):
    """LangChain 서비스
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetLangchainRecommendation = channel.unary_unary(
                '/langchainRecommend.LangchainRecommend/GetLangchainRecommendation',
                request_serializer=langchainRecommend_dot_langchainRecommend__pb2.LangchainRequest.SerializeToString,
                response_deserializer=langchainRecommend_dot_langchainRecommend__pb2.LangchainResponse.FromString,
                )


class LangchainRecommendServicer(object):
    """LangChain 서비스
    """

    def GetLangchainRecommendation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LangchainRecommendServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetLangchainRecommendation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLangchainRecommendation,
                    request_deserializer=langchainRecommend_dot_langchainRecommend__pb2.LangchainRequest.FromString,
                    response_serializer=langchainRecommend_dot_langchainRecommend__pb2.LangchainResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'langchainRecommend.LangchainRecommend', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LangchainRecommend(object):
    """LangChain 서비스
    """

    @staticmethod
    def GetLangchainRecommendation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/langchainRecommend.LangchainRecommend/GetLangchainRecommendation',
            langchainRecommend_dot_langchainRecommend__pb2.LangchainRequest.SerializeToString,
            langchainRecommend_dot_langchainRecommend__pb2.LangchainResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
