# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto.functionCallingWithTypes import functionCallingWithTypes_pb2 as functionCallingWithTypes_dot_functionCallingWithTypes__pb2

GRPC_GENERATED_VERSION = '1.67.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in functionCallingWithTypes/functionCallingWithTypes_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FunctionCallingWithTypesRecommendStub(object):
    """LangChain 서비스
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetFunctionCallingWithTypesRecommendation = channel.unary_unary(
                '/functionCallingWithTypes.FunctionCallingWithTypesRecommend/GetFunctionCallingWithTypesRecommendation',
                request_serializer=functionCallingWithTypes_dot_functionCallingWithTypes__pb2.FunctionCallingWithTypesRequest.SerializeToString,
                response_deserializer=functionCallingWithTypes_dot_functionCallingWithTypes__pb2.FunctionCallingWithTypesResponse.FromString,
                _registered_method=True)


class FunctionCallingWithTypesRecommendServicer(object):
    """LangChain 서비스
    """

    def GetFunctionCallingWithTypesRecommendation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FunctionCallingWithTypesRecommendServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetFunctionCallingWithTypesRecommendation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFunctionCallingWithTypesRecommendation,
                    request_deserializer=functionCallingWithTypes_dot_functionCallingWithTypes__pb2.FunctionCallingWithTypesRequest.FromString,
                    response_serializer=functionCallingWithTypes_dot_functionCallingWithTypes__pb2.FunctionCallingWithTypesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'functionCallingWithTypes.FunctionCallingWithTypesRecommend', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('functionCallingWithTypes.FunctionCallingWithTypesRecommend', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FunctionCallingWithTypesRecommend(object):
    """LangChain 서비스
    """

    @staticmethod
    def GetFunctionCallingWithTypesRecommendation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/functionCallingWithTypes.FunctionCallingWithTypesRecommend/GetFunctionCallingWithTypesRecommendation',
            functionCallingWithTypes_dot_functionCallingWithTypes__pb2.FunctionCallingWithTypesRequest.SerializeToString,
            functionCallingWithTypes_dot_functionCallingWithTypes__pb2.FunctionCallingWithTypesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
