# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: functionCallingWithTypes/functionCallingWithTypes.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'functionCallingWithTypes/functionCallingWithTypes.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7functionCallingWithTypes/functionCallingWithTypes.proto\x12\x18\x66unctionCallingWithTypes\"b\n\x1f\x46unctionCallingWithTypesRequest\x12\x10\n\x08memberId\x18\x01 \x01(\x03\x12\x0e\n\x06gender\x18\x02 \x01(\t\x12\x0c\n\x04year\x18\x03 \x01(\t\x12\x0f\n\x07\x63ommand\x18\x04 \x01(\t\"\x9a\x01\n\x08SongInfo\x12\x12\n\nsongNumber\x18\x01 \x01(\x05\x12\x10\n\x08songName\x18\x02 \x01(\t\x12\x12\n\nartistName\x18\x03 \x01(\t\x12\x12\n\nsongInfoId\x18\x04 \x01(\x03\x12\r\n\x05\x61lbum\x18\x05 \x01(\t\x12\x0c\n\x04isMr\x18\x06 \x01(\x08\x12\x0e\n\x06isLive\x18\x07 \x01(\x08\x12\x13\n\x0bmelonSongId\x18\x08 \x01(\t\"j\n FunctionCallingWithTypesResponse\x12\x35\n\tsongInfos\x18\x01 \x03(\x0b\x32\".functionCallingWithTypes.SongInfo\x12\x0f\n\x07message\x18\x02 \x01(\t2\xca\x01\n!FunctionCallingWithTypesRecommend\x12\xa4\x01\n)GetFunctionCallingWithTypesRecommendation\x12\x39.functionCallingWithTypes.FunctionCallingWithTypesRequest\x1a:.functionCallingWithTypes.FunctionCallingWithTypesResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'functionCallingWithTypes.functionCallingWithTypes_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FUNCTIONCALLINGWITHTYPESREQUEST']._serialized_start=85
  _globals['_FUNCTIONCALLINGWITHTYPESREQUEST']._serialized_end=183
  _globals['_SONGINFO']._serialized_start=186
  _globals['_SONGINFO']._serialized_end=340
  _globals['_FUNCTIONCALLINGWITHTYPESRESPONSE']._serialized_start=342
  _globals['_FUNCTIONCALLINGWITHTYPESRESPONSE']._serialized_end=448
  _globals['_FUNCTIONCALLINGWITHTYPESRECOMMEND']._serialized_start=451
  _globals['_FUNCTIONCALLINGWITHTYPESRECOMMEND']._serialized_end=653
# @@protoc_insertion_point(module_scope)
