# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: langchainAgentRecommend/langchainAgentRecommend.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5langchainAgentRecommend/langchainAgentRecommend.proto\x12\x17langchainAgentRecommend\":\n\x15LangchainAgentRequest\x12\x10\n\x08memberId\x18\x01 \x01(\x03\x12\x0f\n\x07\x63ommand\x18\x02 \x01(\t\"2\n\x0cSearchResult\x12\x12\n\nsongInfoId\x18\x01 \x01(\x03\x12\x0e\n\x06reason\x18\x02 \x01(\t\"U\n\x16LangchainAgentResponse\x12;\n\x0csearchResult\x18\x01 \x03(\x0b\x32%.langchainAgentRecommend.SearchResult2\xa0\x01\n\x17LangchainAgentRecommend\x12\x84\x01\n\x1fGetLangchainAgentRecommendation\x12..langchainAgentRecommend.LangchainAgentRequest\x1a/.langchainAgentRecommend.LangchainAgentResponse\"\x00\x62\x06proto3')



_LANGCHAINAGENTREQUEST = DESCRIPTOR.message_types_by_name['LangchainAgentRequest']
_SEARCHRESULT = DESCRIPTOR.message_types_by_name['SearchResult']
_LANGCHAINAGENTRESPONSE = DESCRIPTOR.message_types_by_name['LangchainAgentResponse']
LangchainAgentRequest = _reflection.GeneratedProtocolMessageType('LangchainAgentRequest', (_message.Message,), {
  'DESCRIPTOR' : _LANGCHAINAGENTREQUEST,
  '__module__' : 'langchainAgentRecommend.langchainAgentRecommend_pb2'
  # @@protoc_insertion_point(class_scope:langchainAgentRecommend.LangchainAgentRequest)
  })
_sym_db.RegisterMessage(LangchainAgentRequest)

SearchResult = _reflection.GeneratedProtocolMessageType('SearchResult', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHRESULT,
  '__module__' : 'langchainAgentRecommend.langchainAgentRecommend_pb2'
  # @@protoc_insertion_point(class_scope:langchainAgentRecommend.SearchResult)
  })
_sym_db.RegisterMessage(SearchResult)

LangchainAgentResponse = _reflection.GeneratedProtocolMessageType('LangchainAgentResponse', (_message.Message,), {
  'DESCRIPTOR' : _LANGCHAINAGENTRESPONSE,
  '__module__' : 'langchainAgentRecommend.langchainAgentRecommend_pb2'
  # @@protoc_insertion_point(class_scope:langchainAgentRecommend.LangchainAgentResponse)
  })
_sym_db.RegisterMessage(LangchainAgentResponse)

_LANGCHAINAGENTRECOMMEND = DESCRIPTOR.services_by_name['LangchainAgentRecommend']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LANGCHAINAGENTREQUEST._serialized_start=82
  _LANGCHAINAGENTREQUEST._serialized_end=140
  _SEARCHRESULT._serialized_start=142
  _SEARCHRESULT._serialized_end=192
  _LANGCHAINAGENTRESPONSE._serialized_start=194
  _LANGCHAINAGENTRESPONSE._serialized_end=279
  _LANGCHAINAGENTRECOMMEND._serialized_start=282
  _LANGCHAINAGENTRECOMMEND._serialized_end=442
# @@protoc_insertion_point(module_scope)
