# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto.langchainAgentRecommend import langchainAgentRecommend_pb2 as langchainAgentRecommend_dot_langchainAgentRecommend__pb2


class LangchainAgentRecommendStub(object):
    """LangChain 서비스
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetLangchainAgentRecommendation = channel.unary_unary(
                '/langchainAgentRecommend.LangchainAgentRecommend/GetLangchainAgentRecommendation',
                request_serializer=langchainAgentRecommend_dot_langchainAgentRecommend__pb2.LangchainAgentRequest.SerializeToString,
                response_deserializer=langchainAgentRecommend_dot_langchainAgentRecommend__pb2.LangchainAgentResponse.FromString,
                )


class LangchainAgentRecommendServicer(object):
    """LangChain 서비스
    """

    def GetLangchainAgentRecommendation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LangchainAgentRecommendServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetLangchainAgentRecommendation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLangchainAgentRecommendation,
                    request_deserializer=langchainAgentRecommend_dot_langchainAgentRecommend__pb2.LangchainAgentRequest.FromString,
                    response_serializer=langchainAgentRecommend_dot_langchainAgentRecommend__pb2.LangchainAgentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'langchainAgentRecommend.LangchainAgentRecommend', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LangchainAgentRecommend(object):
    """LangChain 서비스
    """

    @staticmethod
    def GetLangchainAgentRecommendation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/langchainAgentRecommend.LangchainAgentRecommend/GetLangchainAgentRecommendation',
            langchainAgentRecommend_dot_langchainAgentRecommend__pb2.LangchainAgentRequest.SerializeToString,
            langchainAgentRecommend_dot_langchainAgentRecommend__pb2.LangchainAgentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
